version: '2.1'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - servers
    depends_on:
      - server1
      - server2
      - server3
      - balancer

  balancer:
    build: .
    command: ["lb", "--trace=true"]
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    command: "server"
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    build: .
    command: "server"
    networks:
      - servers
    ports:
      - "8081:8080"

  server3:
    build: .
    command: "server"
    networks:
      - servers
    ports:
      - "8082:8080"

networks:
  servers:
